'use client';
import {flushSync} from 'react-dom';
import {useEffect,useRef,useState} from 'react';
import {landmarks,categories} from '../lib/landmarks';
import type {SceneAPI} from '../lib/scene';
export default function Home(){
 const host=useRef<HTMLDivElement>(null),api=useRef<SceneAPI|null>(null);const [ready,setReady]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState(''),[query,setQuery]=useState(''),[category,setCategory]=useState('All'),[lighting,setLighting]=useState('day'),[panel,setPanel]=useState(true),[labels,setLabels]=useState(true),[paused,setPaused]=useState(false),[help,setHelp]=useState(false),[tour,setTour]=useState(false),[tourIndex,setTourIndex]=useState(0),[exporting,setExporting]=useState(false),[notice,setNotice]=useState('');
 const tourRef=useRef(false),selectRef=useRef<(id:string)=>void>(()=>{});const stops=['peace','customs','hsbc','fosun','aurora','shanghai','swfc','jinmao','pearl','map','rockbund','bridge'];
 function select(id:string){setSelected(id);api.current?.select(id);if(innerWidth<=1100)setPanel(false)}selectRef.current=select;
 useEffect(()=>{let disposed=false;import('../lib/scene').then(({createScene})=>{if(disposed||!host.current)return;try{api.current=createScene(host.current,id=>selectRef.current(id),()=>{tourRef.current=false;setTour(false)});setPanel(innerWidth>680);setPaused(matchMedia('(prefers-reduced-motion: reduce)').matches);setReady(true);(window as any).__shanghai=api.current}catch(e){setError('3D rendering could not start. Try a browser with WebGL enabled, then reload.')}}).catch(()=>setError('The 3D scene could not load. Please reload to try again.'));return()=>{disposed=true;api.current?.dispose() }},[]);
 useEffect(()=>{if(!tour||paused)return;const t=setInterval(()=>{const next=(tourIndex+1)%stops.length;setTourIndex(next);selectRef.current(stops[next])},8000);return()=>clearInterval(t)},[tour,paused,tourIndex]);
 function toggleTour(){if(!tour){select(stops[tourIndex]);if(paused){setPaused(false);api.current?.pause(false)}}tourRef.current=!tour;setTour(!tour)}
 async function exportModel(){setExporting(true);setNotice('Preparing and checking your 3D model…');try{const data=await api.current!.exportGLB();if(location.hostname==='localhost'||location.hostname==='127.0.0.1'){await fetch('/__development-save-glb',{method:'POST',headers:{'Content-Type':'model/gltf-binary'},body:data}).catch(()=>{});}const url=URL.createObjectURL(new Blob([data],{type:'model/gltf-binary'}));const a=document.createElement('a');a.href=url;a.download='shanghai-bund.glb';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);setNotice('GLB downloaded. Water motion, tours, and lighting controls are browser-only.')}catch{setNotice('Export failed. Please try again.')}finally{setExporting(false)}}

 useEffect(()=>{if(!ready)return;const context=(document as any).modelContext;if(!context?.registerTool)return;const life=new AbortController();const register=(tool:any)=>{try{Promise.resolve(context.registerTool(tool,{signal:life.signal})).catch(()=>{})}catch{}};
 register({name:'list_shanghai_places',description:'List the selectable landmarks in this miniature.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>landmarks.map(({id,name,zh,category})=>({id,name,zh,category}))});
 register({name:'navigate_shanghai_place',description:'Select a landmark and fly the camera to it.',inputSchema:{type:'object',properties:{id:{type:'string',enum:landmarks.map(l=>l.id)}},required:['id'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||!landmarks.some(l=>l.id===input.id))throw Error('Unknown landmark');const id=String(input.id);flushSync(()=>{setTour(false);selectRef.current(id)});await new Promise(r=>setTimeout(r,2500));return{id:input.id,status:'selected'}}});
 register({name:'set_shanghai_lighting',description:'Switch the visible scene to day, sunset, or night.',inputSchema:{type:'object',properties:{mode:{type:'string',enum:['day','sunset','night']}},required:['mode'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{if(!input||!['day','sunset','night'].includes(input.mode))throw Error('Unknown lighting mode');const mode=String(input.mode);flushSync(()=>setLighting(mode));api.current?.light(mode);await new Promise(r=>setTimeout(r,1800));return{mode:input.mode}}});return()=>life.abort();},[ready]);
 const l=landmarks.find(l=>l.id===selected);const filtered=landmarks.filter(l=>(category==='All'||l.category===category)&&`${l.name} ${l.zh}`.toLowerCase().includes(query.toLowerCase()));
 return <main className={`explorer ${panel?'panel-open':''}`}>
 <div ref={host} className="scene"/>
 <header className="topbar"><div className="brand"><span className="brand-mark">上</span><div><h1>SHANGHAI<span> / 上海</span></h1><p>BETWEEN TWO SHORES</p></div></div><div className="light-switch" aria-label="Time of day">{['day','sunset','night'].map((t,i)=><button key={t} aria-pressed={lighting===t} className={lighting===t?'active':''} onClick={()=>{setLighting(t);api.current?.light(t)}}><span>{['☀','◒','☾'][i]}</span>{t}</button>)}</div><button className="icon-button help" aria-label="How to explore" onClick={()=>setHelp(true)}>?</button></header>
 <button className="directory-toggle" onClick={()=>setPanel(!panel)} aria-expanded={panel}>☷ <span>{panel?'Hide places':'Explore places'}</span></button>
 {panel&&<aside className="directory"><div className="section-heading"><span>THE RIVER & THE CITY</span><b>{landmarks.length} places</b></div><h2>A city to get lost in.</h2><label className="search"><span>⌕</span><input placeholder="Find a place / 搜索地标" aria-label="Search landmarks" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="filters">{categories.map(c=><button key={c} aria-pressed={c===category} className={c===category?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}</div><div className="place-list">{filtered.map((p,i)=><button key={p.id} className={`place ${selected===p.id?'selected':''}`} onClick={()=>{setTour(false);select(p.id)}}><span className={`place-symbol ${p.category.toLowerCase()}`}>{p.category==='Skyline'?'▥':p.category==='Culture'?'▧':p.category==='Shopping'?'◇':'▤'}</span><span><strong>{p.name}</strong><small>{p.zh}</small></span><span className="arrow">↗</span></button>)}{!filtered.length&&<p className="empty">No places match your search.</p>}</div><div className="directory-foot"><span className="live-dot"/> <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors</a></div></aside>}
 <div className="scene-title"><span>31°14′ N &nbsp; 121°29′ E</span><p>The Bund <i>&</i> Lujiazui</p><small>外滩 · 陆家嘴</small></div>
 {l&&<section className="detail" aria-live="polite"><button className="close" aria-label="Close landmark description" onClick={()=>setSelected('')}>×</button><span className="eyebrow">{l.category} / {l.address.includes('Puxi')?'PUXI':'PUDONG'}</span><h2>{l.name}</h2><p className="chinese">{l.zh}</p><p>{l.description}</p><small>{l.address}</small><a href={l.source} target="_blank" rel="noreferrer">Read more ↗</a></section>}
 <div className="view-tools"><button aria-label="Toggle place labels" className={labels?'active':''} onClick={()=>{setLabels(!labels);api.current?.labels(!labels)}}>Aa</button><button aria-label={paused?'Resume all animation':'Pause all animation'} onClick={()=>{setPaused(!paused);api.current?.pause(!paused)}}>{paused?'▶':'Ⅱ'}</button><button aria-label="Reset view" onClick={()=>{setTour(false);api.current?.view('overview')}}>⌂</button></div>
 <footer className="bottom-bar"><div className="view-presets"><span>VIEWS</span>{[['overview','Overview'],['bund','The Bund'],['skyline','Lujiazui']].map(([id,name])=><button key={id} onClick={()=>{setTour(false);api.current?.view(id)}}>{name}</button>)}</div><div className="tour-controls"><button className="tour-button" onClick={toggleTour}>{tour?'Ⅱ Pause tour':'▷ Auto tour'} <span>自动漫游</span></button>{(tour||selected===stops[tourIndex])&&<><button aria-label="Next tour stop" onClick={()=>{const n=(tourIndex+1)%stops.length;setTourIndex(n);select(stops[n])}}>→</button><button aria-label="Exit tour" onClick={()=>{setTour(false);setTourIndex(0);api.current?.view('overview')}}>×</button></>}</div><button className="export" disabled={!ready||exporting} onClick={exportModel}>↓ <span>{exporting?'Exporting…':'Download 3D'}</span></button></footer>
 <div className="interaction-hint">Drag to orbit <span>·</span> Scroll to zoom <span>·</span> Click to fly</div>
 {!ready&&<div className="loading"><div className="loading-mark">沪</div><h2>{error?'Unable to open Shanghai':'Opening the waterfront'}</h2><p>{error||'Building a little city, one landmark at a time.'}</p>{error&&<button onClick={()=>location.reload()}>Reload</button>}</div>}
 {notice&&<div className="toast" role="status">{notice}<button aria-label="Dismiss notification" onClick={()=>setNotice('')}>×</button></div>}
 {help&&<div className="modal-backdrop" onClick={()=>setHelp(false)}><section className="help-modal" role="dialog" aria-modal="true" aria-labelledby="help-title" onClick={e=>e.stopPropagation()}><button className="close" aria-label="Close help" onClick={()=>setHelp(false)}>×</button><span className="eyebrow">YOUR POCKET SHANGHAI</span><h2 id="help-title">Take the scenic route.</h2><dl><dt>Look around</dt><dd>Drag to rotate. Scroll or pinch to zoom. Right-drag or use two fingers to pan.</dd><dt>Go somewhere</dt><dd>Click a building, its label, or a place in the directory to fly over. Drag to interrupt the flight.</dd><dt>Chase the light</dt><dd>Switch between day, sunset, and night using the controls above.</dd><dt>Let the city guide you</dt><dd>Auto tour visits 12 stops. Pause, skip to the next stop, or exit. Manual interaction pauses the tour.</dd><dt>Make time stand still</dt><dd>The Ⅱ control pauses boats, traffic, water, and tour progression. Reduced-motion settings start with animation paused.</dd><dt>Keep the miniature</dt><dd>Download 3D exports a GLB for Blender and other 3D tools. Browser animations, tours, and lighting presets are not included.</dd></dl><h3>About this miniature</h3><p>Roads, riverbanks, and city outlines come from OpenStreetMap at a consistent scale. Landmark façades are photo-guided interpretations; missing building heights are estimated. This is not a survey model. Museum interiors are not modeled.</p><a href="/guide.html" target="_blank">Full guide, references & credits ↗</a></section></div>}
 </main>
}
