import verifiedPositions from './verified-positions.json';
import mapData from './map-data.json';
export type Landmark = { id:string; name:string; zh:string; category:string; x:number; z:number; h:number; w:number; d:number; kind:string; description:string; source:string; address:string };
const bund='https://english.shanghai.gov.cn/en-ScenicSpots/20231205/584672cc6d044eabb5f7f6fc9049a19f.html';
const art='https://english.shanghai.gov.cn/en-CityTour/20240528/c72d035314474efd8820f3c94ccd97c8.html';
const shop='https://english.shanghai.gov.cn/en-ShanghaiStyle/20260703/62d8c9568b7641b3ac864e93762d78c3.html';
export const landmarks:Landmark[]=[
{id:'auroraplaza',name:'Aurora Plaza',zh:'震旦国际大楼',category:'Skyline',x:68.4,z:-13,h:40.7,w:11,d:13,kind:'led',description:'Aurora Plaza’s gold-glass waterfront façade incorporates a large LED screen, confirmed by its glass supplier. Switch to night to see I ❤️ SH, a custom message created for this miniature.',source:'https://www.taiwanglass.com/application_detail.php?id=527&langeno=en&sid=159',address:'99 Fucheng Road · Pudong'},
{id:'pearl',name:'Oriental Pearl Tower',zh:'东方明珠',category:'Skyline',x:63,z:-66,h:103,w:17,d:17,kind:'pearl',description:'Stacked pink spheres and three splayed legs give this broadcasting tower its unmistakable silhouette. It anchors the northern end of the Lujiazui skyline.',source:art,address:'1 Century Avenue · Pudong'},
{id:'shanghai',name:'Shanghai Tower',zh:'上海中心大厦',category:'Skyline',x:135,z:29,h:139,w:23,d:23,kind:'twist',description:'A 632-metre tower with a twisting glass envelope. Its rounded, tapering form rises above the financial district.',source:'https://en.shanghaitower.com/ProjectIntroduction.html',address:'479 Lujiazui Ring Road · Pudong'},
{id:'swfc',name:'World Financial Center',zh:'上海环球金融中心',category:'Skyline',x:164,z:0,h:108,w:21,d:12,kind:'bottle',description:'The Shanghai World Financial Center is recognized by the large opening near its summit. Its crisp profile contrasts with its curved neighbor.',source:'https://english.shanghai.gov.cn/en-PlanANightOut/20260608/6a9a6187e3f54378b534ec023a0b805a.html',address:'100 Century Avenue · Pudong'},
{id:'jinmao',name:'Jin Mao Tower',zh:'金茂大厦',category:'Skyline',x:127,z:-9,h:103,w:20,d:20,kind:'pagoda',description:'A tiered skyscraper whose repeated setbacks recall a traditional Chinese pagoda. A pointed crown completes its layered silhouette.',source:art,address:'88 Century Avenue · Pudong'},
{id:'customs',name:'Customs House',zh:'江海关大楼',category:'Heritage',x:-68,z:15,h:20,w:19,d:16,kind:'clock',description:'The Bund’s landmark clock tower rises above a formal stone façade. Together with the neighboring former HSBC Building, it defines the historic waterfront.',source:bund,address:'13 Zhongshan East 1st Road · Puxi'},
{id:'hsbc',name:'Former HSBC Building',zh:'原汇丰银行大楼',category:'Heritage',x:-69,z:40,h:15,w:22,d:20,kind:'dome',description:'A grand domed banking building with a columned entrance. It is also known as the Shanghai Pudong Development Bank Building; represented here only once.',source:bund,address:'12 Zhongshan East 1st Road · Puxi'},
{id:'peace',name:'Peace Hotel',zh:'和平饭店',category:'Heritage',x:-66,z:-42,h:23,w:18,d:20,kind:'peace',description:'The hotel’s green pyramidal roof is a familiar Bund landmark. It stands at the eastern end of Nanjing Road.',source:art,address:'20 Nanjing East Road · Puxi'},
{id:'boc',name:'Bank of China Building',zh:'中国银行大楼',category:'Heritage',x:-64,z:-68,h:18,w:18,d:20,kind:'china',description:'A monumental bank building beside the Peace Hotel, with a symmetrical façade and a roofline influenced by Chinese architecture.',source:bund,address:'23 Zhongshan East 1st Road · Puxi'},
{id:'bridge',name:'Waibaidu Bridge',zh:'外白渡桥',category:'Heritage',x:-43,z:-113,h:8,w:12,d:27,kind:'bridge',description:'A steel truss bridge spanning Suzhou Creek near its meeting with the Huangpu. Watch the miniature traffic crossing its deck.',source:bund,address:'Suzhou Creek mouth · Puxi'},
{id:'rockbund',name:'Rockbund Art Museum',zh:'上海外滩美术馆',category:'Culture',x:-104,z:-87,h:12,w:13,d:16,kind:'artdeco',description:'A contemporary art museum in a historic Art Deco building within the Rockbund neighborhood, a short distance inland from the waterfront.',source:art,address:'20 Huqiu Road · Puxi'},
{id:'history',name:'Bund History Museum',zh:'外滩历史纪念馆',category:'Culture',x:-35,z:-89,h:8,w:9,d:9,kind:'monument',description:'A museum associated with the monument in Huangpu Park, telling the story of the Bund. The miniature marks its location with the above-ground memorial; galleries are not modeled.',source:bund,address:'Huangpu Park · Puxi'},
{id:'fosun',name:'Fosun Foundation',zh:'复星艺术中心',category:'Culture',x:-69,z:135,h:9,w:17,d:13,kind:'fosun',description:'An arts venue at the Bund Finance Center. Its bronze-colored, curtain-like exterior is translated into layered vertical tubes in this miniature.',source:'https://www.fosunfoundation.com/en/visiting',address:'600 Zhongshan East 2nd Road · Puxi'},
{id:'aurora',name:'Aurora Museum',zh:'震旦博物馆',category:'Culture',x:63,z:75,h:9,w:19,d:13,kind:'museum',description:'A museum on the Pudong waterfront known for its collection of Chinese antiquities. Its low exhibition building is shown beside a simplified Aurora tower.',source:art,address:'99 Fucheng Road · Pudong'},
{id:'map',name:'Museum of Art Pudong',zh:'浦东美术馆',category:'Culture',x:43,z:-38,h:10,w:21,d:18,kind:'map',description:'A contemporary art destination beside the Huangpu River. Its pale geometric massing and large river-facing window overlook the Bund.',source:art,address:'2777 Binjiang Avenue · Pudong'},
{id:'bfc',name:'BFC Bund Finance Center',zh:'外滩金融中心',category:'Shopping',x:-99,z:131,h:33,w:28,d:28,kind:'bfc',description:'A mixed-use shopping, dining, and office destination on the southern Bund. Fosun Foundation occupies a separate cultural building within the complex.',source:'https://english.shanghai.gov.cn/en-PlanANightOut/20231217/c408152e2b10479389bfd015ee0bd68d.html',address:'600 Zhongshan East 2nd Road · Puxi'},
{id:'bund18',name:'Bund 18',zh:'外滩十八号',category:'Shopping',x:-67,z:-17,h:12,w:17,d:16,kind:'classic',description:'A historic Bund building adapted for shopping and dining. Its ornate stone exterior remains part of the continuous waterfront streetscape.',source:shop,address:'18 Zhongshan East 1st Road · Puxi'},
{id:'ifc',name:'Shanghai IFC Mall',zh:'上海国金中心商场',category:'Shopping',x:94,z:-22,h:57,w:24,d:22,kind:'ifc',description:'A shopping destination at the base of the IFC complex in Lujiazui. The model includes its podium and a simplified pair of office towers.',source:'https://english.shanghai.gov.cn/en-LatestEvents/20251218/9e8e4ed37c8641eca8c1fe530c4496a7.html',address:'8 Century Avenue · Pudong'},
{id:'superbrand',name:'Super Brand Mall',zh:'正大广场',category:'Shopping',x:64,z:-5,h:14,w:22,d:24,kind:'mall',description:'A large shopping and dining complex near the Oriental Pearl Tower, positioned between the riverfront and the heart of Lujiazui.',source:'https://english.shanghai.gov.cn/en-PlanANightOut/20260608/6a9a6187e3f54378b534ec023a0b805a.html',address:'168 Lujiazui West Road · Pudong'},
{id:'nanjing',name:'Nanjing Road East',zh:'南京东路步行街',category:'Shopping',x:-143,z:-42,h:13,w:75,d:25,kind:'street',description:'The eastern stretch of Shanghai’s celebrated shopping street leads inland from the Bund. A pedestrian corridor and small retail blocks suggest its lively streetscape.',source:bund,address:'Nanjing East Road · Puxi'},
{id:'convention',name:'International Convention Center',zh:'上海国际会议中心',category:'Skyline',x:40,z:-76,h:16,w:24,d:18,kind:'convention',description:'A riverfront convention venue distinguished by its spherical architectural features, close to the Oriental Pearl Tower.',source:'https://www.shicc.net/',address:'2727 Binjiang Avenue · Pudong'},
{id:'club',name:'Shanghai Club Building',zh:'上海总会大楼',category:'Heritage',x:-75,z:91,h:11,w:21,d:17,kind:'classic',description:'A richly detailed historic building on the southern stretch of the Bund, now part of the Waldorf Astoria hotel complex.',source:bund,address:'2 Zhongshan East 1st Road · Puxi'},
];
for (const l of landmarks) {if(l.id==='peace')l.h=17;if(l.id==='hsbc')l.h=13.2;const location=(mapData.locations as Record<string,{x:number;z:number}>)[l.id];if(location){l.x=location.x;l.z=location.z;}}
for(const l of landmarks){const p=(verifiedPositions as Record<string,{x:number;z:number}>)[l.id];if(p){l.x=p.x;l.z=p.z;}}
// Preserve both detailed models while leaving a narrow lane between their outer cornices.
landmarks.find(l=>l.id==='hsbc')!.z += 6.5;
// Limit footprint adjustments to five percent; preserve all building heights.
for(const l of landmarks){if(['swfc','boc','rockbund','bund18','customs','hsbc'].includes(l.id)){l.w*=.95;l.d*=.95;}}
export const categories=['All','Heritage','Skyline','Culture','Shopping'];
